# core

> Fill in a module description here

In [ ]:
%load_ext autoreload
%autoreload 2

In [ ]:
#| default_exp monte

In [ ]:
#| hide
from nbdev.showdoc import *

In [ ]:
#|export
from fastcore.all import *
import polvo as pv
import truco as tr
import numpy as np
import random

/home/lgvaz/miniconda3/envs/truco/lib/python3.10/site-packages/polvo/utils/logging.py:8: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm


In [ ]:
def sample_one(i):
    t2_cards = random.sample(card_pool, 6)
#     faceup = round_cards[0]
#     t2_cards = round_cards[1:]
    
    # TODO: don't need to return trump card
    trump, round_rank = tr.get_trump_round_rank(faceup)
    
    t1_ranks = tr.cards2ranks(t1_cards, round_rank)
    t2_ranks = tr.cards2ranks(t2_cards, round_rank)
    
    t1_ranks = np.sort(t1_ranks)[-1:-4:-1]
    t2_ranks = np.sort(t2_ranks)[-1:-4:-1]
    
    round_result = (t1_ranks - t2_ranks)
    return round_result

In [ ]:
# t1_cards = '3d 3h ks'.split()
# t1_cards = '5c 5h 6s'.split()
t1_cards = '3d 3h ks'.split()
faceup = '4d'
# t1_cards = '3d 3h ks'.split()
card_pool = list(set(tr.card_pool) - set(t1_cards+[faceup]))

In [ ]:
results = np.array(parallel(sample_one, range(10000), progress=pv.pbar))

In [ ]:
results_sign = np.sign(results)

In [ ]:
wins = np.sign(results_sign.sum(axis=1))
score, counts = np.unique(wins, return_counts=True)
print(''.join(f'{s}: {c/len(results)}\n' for s, c in zip(score, counts)))

-1: 0.3443
0: 0.1477
1: 0.508



In [ ]:
_, counts = np.unique(results_sign, return_counts=True)
loose_pct, draw_pct

(array([-1,  0,  1]), array([ 8855,  3937, 17208]))

In [ ]:
result = results[-2]
result

array([-1,  0, -2])

In [ ]:
np.sign(result)

array([-1,  0, -1])

In [ ]:
np.sign()

In [ ]:
#| export
def foo(): pass

In [ ]:
#| hide
import nbdev; nbdev.nbdev_export()

ModuleNotFoundError: No module named 'nbdev'